lib/command.js, lib/vorpal.js, test/integration.js
Kill the program on registering duplicate alias with a command.
=> Throw error on duplicate alias

README.md
... and remove some trailing spaces.
=> Fix 'List of awesome extensions' & 'Vorpal extensions' URLs

README.md
Hi, I've been reading documentation and I've found that some of the readme API URLs are incorrect.
=> Fix API URLs

lib/command-instance.js
See: https://github.com/dthree/vorpal/issues/33
=> Fix: vorpal.exec never fires callback with piped commands when using promises #33

package.json
`Inquirer.js` last release fixes the bug occurring when you start your node app into debug mode.
[fix commit](https://github.com/knownasilya/Inquirer.js/commit/f080fb9bc93dfa592700f327b1e73ae6f93ae343)
=> update Inquirer.js version

lib/ui.js, test/integration.js
The client_keypress event wasn't fired because it was emitted from ui module and not from vorpal instance.
I have also added some tests to check if the events work correctly
=> Fix "client_keypress" event

lib/command-instance.js, lib/command.js, lib/session.js, lib/vorpal.js, test/integration.js
Added a validate function to allow arguments validation.
Arguments are considered valid if no errors are throw from that function.
=> Validate command arguments #40

lib/command-instance.js, test/integration.js
=> Log and emit event when piped commands error 

lib/util.js, test/integration.js, test/util/server.js
=> Fixing silent failure of missing required options

lib/command-instance.js, lib/command.js, lib/session.js, lib/ui.js, lib/vorpal.js, package.json, test/integration.js
CTRL + C will cancel a running command (if any running) by calling the cancel function registered and the cancel function on the promise if it exists
#45
=> Added ability to cancel commands with CTRL + C

lib/command-instance.js, lib/session.js, test/integration.js
Call validation function with the same context as action function.
=> Call validate function with correct context

examples/prompt/prompt.js, lib/ui.js
See: https://github.com/dthree/vorpal/issues/67
=> Mask password characters while typing #67

dist/vorpal-commons.js, dist/vorpal.js, lib/vorpal-commons.js, lib/vorpal.js
Please review as I only had a few minutes to go through this but it works as expected.
=> removed y/N and updated exit message

dist/history.js, lib/history.js, test/integration.js
bash style
added breaking test, and fix
it's a matter of opinion of course, so i can understand if you don't want to have history behave this way
=> ignore consecutive duplicates in history

test/index.js
mode's init() context should be the same as action() context
=> breaking test for mode init vs action context

dist/autocomplete.js, lib/autocomplete.js, test/autocomplete.js
hey @dthree this is a small set of the autocomplete changes I made against a previous build a few months ago - I still see some of these problems in 1.10.10, this fixes those cases and adds tests to make sure we never regress
=> Fixes multiple matching commands for autocomplete

dist/option.js, dist/ui.js, dist/util.js, dist/vorpal.js, lib/ui.js
=> Fix for undefined check

lib/ui.js
This change fix the issue where inquirer validate errors do not show on vorpal
Issue: https://github.com/dthree/vorpal/issues/69
=> fix issue where inquirer validate errors don't show

lib/vorpal.js
Added 'vorpal_exit' event for exiting hook
=> Added 'vorpal_exit' event

index.html
Removed trailing comma in prompt demo.
=> syntax fix in prompt demo

CHANGELOG.md, lib/command-instance.js, lib/command.js, lib/helpers/camelCase.js, lib/session.js, lib/vorpal.js, package.json
Converts `Command` and `CommandInstance` to ES2015.
=> Convert commands to ES2015

lib/history.js
All tests pass and the file runs in Node without babel. The linter passes for this file, aside from rules would have me change existing variable names (no-underscore-dangle, no-shadow). Let me know if I should take care of those errors as well, I didn't want to jump the gun.
=> Update lib/history.js to ES2015

lib/ui.js
=> Converted UI to ES2015

lib/session.js
Allow user to access the raw command string
=> Allow user to access the raw command string
